In [1]:
pwd()

'/Users/cindyhu/Documents/Courses/CS171/teamAqua/ucmr-3-occurrence-data'

In [2]:
import pandas as pd
import numpy as np

In [10]:
df = pd.read_csv('UCMR3_reduced.csv')

In [11]:
df.head(10)

,Unnamed: 0,PWSID,CollectionDate,SampleID,Contaminant,AnalyticalResultValue,indices,POPULATION_SERVED_COUNT
0,1,MI0004370,03/11/2014,201403130319AM,strontium,98.000000,2.514105,41706
1,2,MI0004370,03/11/2014,201403130319AM,PFOS,0.028284,0.000000,41706
2,3,MI0004370,03/11/2014,201403130319AM,bromomethane,0.141421,0.000000,41706
3,4,MI0004370,03/11/2014,201403130319AM,chloromethane,0.141421,0.000000,41706
4,5,MI0004370,03/11/2014,201403130319AM,vanadium,0.141421,0.000000,41706
5,6,MI0004370,03/11/2014,201403130319AM,"1,2,3-trichloropropane",0.021213,0.000000,41706
6,7,MI0004370,03/11/2014,201403130319AM,chromium,0.230000,0.060698,41706
7,8,MI0004370,03/11/2014,201403130319AM,"1,4-dioxane",0.049497,0.000000,41706
8,9,MI0004370,03/11/2014,201403130319AM,PFOA,0.014142,0.000000,41706
9,10,MI0004370,03/11/2014,201403130319AM,cobalt,0.707107,0.000000,41706

In [12]:
df['Contaminant'].unique()

array(['strontium', 'PFOS', 'bromomethane', 'chloromethane', 'vanadium',
       '1,2,3-trichloropropane', 'chromium', '1,4-dioxane', 'PFOA',
       'cobalt', 'PFNA', 'PFHpA', 'PFHxS', 'chlorate', 'PFBS', 'HCFC-22',
       '1,3-butadiene', 'Halon 1011', 'molybdenum', 'chromium-6',
       '1,1-dichloroethane', 'estriol', 'equilin',
       '17-alpha-ethynylestrad', '17-beta-estradiol',
       '4-androstene-3,17-dion', 'testosterone', 'estrone', 'manganese',
       'germanium', 'tellurium', 'sec-butylbenzene', 'n-propylbenzene',
       'Enterococci', 'Male specific phage', 'Somatic phage',
       'Enteroviruses (cell cu', 'Enteroviruses (RT-qPCR',
       'Noroviruses GIA', 'Noroviruses GIB', 'Noroviruses GII',
       'Aerobic spores', 'Total coliforms', 'E. coli'], dtype=object)

In [13]:
#output dataset for number of population impacted by each contaminant
df_detect = df.loc[df['indices']>0]
import numpy as np
#df_detect.drop_duplicates(subset=['PWSID','Contaminant','POPULATION_SERVED_COUNT']).shape()
df_detect_unique = df_detect.reindex(columns=['PWSID','Contaminant','POPULATION_SERVED_COUNT']).drop_duplicates()
df_detect_unique.reindex(columns=['Contaminant','POPULATION_SERVED_COUNT']).groupby(['Contaminant']).sum().to_csv('pop_detect.csv')

In [14]:
subset = df.reindex(columns=['PWSID','Contaminant','AnalyticalResultValue','indices'])

In [15]:
#aggregate by pwsid
f={'AnalyticalResultValue':['max','count'],'indices':['max','count']}
ucmr_by_pwsid = subset.groupby(["PWSID",'Contaminant']).agg(f).unstack()

In [16]:
ucmr_by_pwsid.head(10)

            AnalyticalResultValue                                       \
                              max
Contaminant    1,1-dichloroethane 1,2,3-trichloropropane 1,3-butadiene
PWSID
AK2110342                0.021213               0.021213      0.070711
AK2210906                0.021213               0.021213      0.070711
AK2211423                0.021213               0.021213      0.070711
AK2212021                0.021213               0.021213      0.070711
AK2224646                0.021213               0.021213      0.070711
AK2240456                0.021213               0.021213      0.070711
AK2240757                0.021213               0.021213      0.070711
AK2243006                     NaN                    NaN           NaN
AK2310730                0.040000               0.021213      0.070711
AK2310900                0.030000               0.021213      0.070711

                                                                  \

Contaminant 1,4-dioxane 17-alpha-ethynylestrad 17-beta-estradiol
PWSID
AK2110342      0.049497                    NaN               NaN
AK2210906      0.049497               0.000636          0.000283
AK2211423      0.049497                    NaN               NaN
AK2212021      0.049497                    NaN               NaN
AK2224646      0.049497                    NaN               NaN
AK2240456      0.049497                    NaN               NaN
AK2240757      0.049497                    NaN               NaN
AK2243006           NaN               0.000636          0.000283
AK2310730      0.049497                    NaN               NaN
AK2310900      0.049497                    NaN               NaN

                                                                       \

Contaminant 4-androstene-3,17-dion Aerobic spores E. coli Enterococci
PWSID
AK2110342                      NaN            NaN     NaN         NaN
AK2210906                 0.000212            NaN     NaN         NaN
AK2211423                      NaN            NaN     NaN         NaN
AK2212021                      NaN            NaN     NaN         NaN
AK2224646                      NaN            NaN     NaN         NaN
AK2240456                      NaN            NaN     NaN         NaN
AK2240757                      NaN            NaN     NaN         NaN
AK2243006                 0.000212            NaN     NaN         NaN
AK2310730                      NaN            NaN     NaN         NaN
AK2310900                      NaN            NaN     NaN         NaN

              ...    indices                                                 \
              ...      count
Contaminant   ...    estrone germanium manganese molybdenum n-propylbenzene
PWSID         ...
AK2110342     ...        NaN       NaN       NaN       10.0             NaN
AK2210906     ...       28.0       NaN       NaN       32.0             NaN
AK2211423     ...        NaN       NaN       NaN       12.0             NaN
AK2212021     ...        NaN       4.0       4.0        4.0             2.0
AK2224646     ...        NaN       NaN       NaN       12.0             NaN
AK2240456     ...        NaN       8.0       8.0        8.0             4.0
AK2240757     ...        NaN      10.0      10.0       10.0             6.0
AK2243006     ...        2.0       NaN       NaN        NaN             NaN
AK2310730     ...        NaN       NaN       NaN        4.0             NaN
AK2310900     ...        NaN       NaN       NaN        4.0             NaN



Contaminant sec-butylbenzene strontium tellurium testosterone vanadium
PWSID
AK2110342                NaN      10.0       NaN          NaN     10.0
AK2210906                NaN      32.0       NaN         28.0     32.0
AK2211423                NaN      12.0       NaN          NaN     12.0
AK2212021                2.0       4.0       4.0          NaN      4.0
AK2224646                NaN      12.0       NaN          NaN     12.0
AK2240456                4.0       8.0       8.0          NaN      8.0
AK2240757                6.0      10.0      10.0          NaN     10.0
AK2243006                NaN       NaN       NaN          2.0      NaN
AK2310730                NaN       4.0       NaN          NaN      4.0
AK2310900                NaN       4.0       NaN          NaN      4.0

[10 rows x 176 columns]

In [17]:
#output by pws result, manually remove empty cells from stack/unstack process, read in ucmrByPwsid_e.csv
ucmr_by_pwsid.to_csv('ucmrByPwsid.csv')

In [32]:
#aggregate by zip
zip = pd.read_table('UCMR3_Zipcodes.txt')
ucmr_by_pwsid = pd.read_csv('ucmrByPwsid_e.csv')

In [33]:
zip['PWSID'] = [ i.lstrip('0') for i in zip['PWSID'] ]

In [34]:
result = pd.merge(ucmr_by_pwsid, zip, on='PWSID')

In [3]:
#aggregate zip to county
#data source: US department of housing and urban development 
#https://www.huduser.gov/portal/datasets/usps_crosswalk.html
county = pd.read_csv('ZIP_COUNTY_032017.csv')
county['ZIPCODE']=[str(i).zfill(5) for i in county['ZIP']]
subset = county.reindex(columns=['ZIPCODE','COUNTY'])
subset.to_csv('zipcode_county_map.csv')

In [38]:
byzip1=pd.concat([result.filter(regex=("count.*")), result['ZIPCODE']], axis=1).groupby(["ZIPCODE"]).sum()

In [39]:
byzip2=pd.concat([result.filter(regex=("max.*")), result['ZIPCODE']], axis=1).groupby(["ZIPCODE"]).max()

In [40]:
pd.concat([byzip1,byzip2],axis=1).to_csv('ucmrByZip.csv')

In [41]:
ucmr_by_zip = pd.read_csv('ucmrByZip.csv')

In [42]:
ucmr_by_zip['ZIPCODE'] = [ i.rstrip('-') for i in ucmr_by_zip['ZIPCODE'] ]

In [43]:
ucmr_by_zip['ZIPCODE'] = [str(i).zfill(5) for i in ucmr_by_zip['ZIPCODE']]

In [44]:
result2 = pd.merge(ucmr_by_zip, subset, on='ZIPCODE')

In [45]:
result2.head(10)

,ZIPCODE,"AnalyticalResultValue.count.1,1-dichloroethane","AnalyticalResultValue.count.1,2,3-trichloropropane","AnalyticalResultValue.count.1,3-butadiene","AnalyticalResultValue.count.1,4-dioxane",AnalyticalResultValue.count.17-alpha-ethynylestrad,AnalyticalResultValue.count.17-beta-estradiol,"AnalyticalResultValue.count.4-androstene-3,17-dion",AnalyticalResultValue.count.Aerobic spores,AnalyticalResultValue.count.E. coli,...,indices.max.germanium,indices.max.manganese,indices.max.molybdenum,indices.max.n-propylbenzene,indices.max.sec-butylbenzene,indices.max.strontium,indices.max.tellurium,indices.max.testosterone,indices.max.vanadium,COUNTY
0,00765,8.0,8.0,8.0,8.0,8.0,8.0,8.0,NaN,NaN,...,NaN,NaN,0.000000,NaN,NaN,2.753328,NaN,0.0,0.342423,72147
1,01001,8.0,8.0,8.0,8.0,4.0,4.0,4.0,NaN,NaN,...,NaN,NaN,0.000000,NaN,NaN,1.778151,NaN,0.0,0.311754,25013
2,01002,16.0,16.0,16.0,16.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,0.000000,NaN,NaN,2.865301,NaN,NaN,0.267172,25015
3,01002,16.0,16.0,16.0,16.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,0.000000,NaN,NaN,2.865301,NaN,NaN,0.267172,25011
4,01013,4.0,4.0,4.0,4.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,0.000000,NaN,NaN,1.936179,NaN,NaN,0.000000,25013
5,01014,4.0,4.0,4.0,4.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,0.000000,NaN,NaN,1.936179,NaN,NaN,0.000000,25013
6,01020,4.0,4.0,4.0,4.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,0.000000,NaN,NaN,1.936179,NaN,NaN,0.000000,25013
7,01021,4.0,4.0,4.0,4.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,0.000000,NaN,NaN,1.936179,NaN,NaN,0.000000,25013
8,01022,4.0,4.0,4.0,4.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,0.000000,NaN,NaN,1.936179,NaN,NaN,0.000000,25013
9,01027,8.0,8.0,8.0,8.0,2.0,2.0,2.0,NaN,NaN,...,NaN,NaN,0.230449,NaN,NaN,2.806180,NaN,0.0,0.607455,25015

In [46]:
#result2.groupby(["COUNTY"]).max().to_csv('ucmrByCounty.csv')

byct1=pd.concat([result2.filter(regex=("count.*")), result2['COUNTY']], axis=1).groupby(["COUNTY"]).sum()
byct2=pd.concat([result2.filter(regex=("max.*")), result2['COUNTY']], axis=1).groupby(["COUNTY"]).max()
pd.concat([byct1,byct2],axis=1).to_csv('ucmrByCounty.csv')

In [47]:
ucmr_by_county = pd.read_csv('ucmrByCounty.csv')

In [48]:
#add county name to the dataset
#data source: the national bureau of economic research
#http://www.nber.org/data/ssa-fips-state-county-crosswalk.html
countyname = pd.read_csv('ssa_fips_state_county2017.csv').reindex(columns=['fipscounty','county','state'])

In [49]:
countyname.columns = ['COUNTY', 'countyname','state']
ucmr_by_county2 = pd.merge(ucmr_by_county, countyname, on='COUNTY')

In [52]:
ucmr_by_county2.countyname = ucmr_by_county2.countyname.str.title()

In [53]:
ucmr_by_county2.head(10)

,COUNTY,"AnalyticalResultValue.count.1,1-dichloroethane","AnalyticalResultValue.count.1,2,3-trichloropropane","AnalyticalResultValue.count.1,3-butadiene","AnalyticalResultValue.count.1,4-dioxane",AnalyticalResultValue.count.17-alpha-ethynylestrad,AnalyticalResultValue.count.17-beta-estradiol,"AnalyticalResultValue.count.4-androstene-3,17-dion",AnalyticalResultValue.count.Aerobic spores,AnalyticalResultValue.count.E. coli,...,indices.max.manganese,indices.max.molybdenum,indices.max.n-propylbenzene,indices.max.sec-butylbenzene,indices.max.strontium,indices.max.tellurium,indices.max.testosterone,indices.max.vanadium,countyname,state
0,1001,59.0,59.0,59.0,59.0,4.0,4.0,4.0,NaN,NaN,...,2.650008,0.255273,0.0,0.0,3.636822,0.0,0.0,0.382917,Autauga,AL
1,1003,122.0,122.0,122.0,122.0,NaN,NaN,NaN,NaN,NaN,...,NaN,0.000000,NaN,NaN,2.753328,NaN,NaN,0.301030,Baldwin,AL
2,1005,14.0,14.0,14.0,14.0,32.0,32.0,32.0,NaN,NaN,...,NaN,0.000000,NaN,NaN,1.937852,NaN,0.0,0.361728,Barbour,AL
3,1007,8.0,8.0,8.0,8.0,8.0,8.0,8.0,NaN,NaN,...,NaN,0.146128,NaN,NaN,2.564271,NaN,0.0,0.301030,Bibb,AL
4,1009,80.0,80.0,80.0,80.0,NaN,NaN,NaN,NaN,NaN,...,0.000000,0.079181,0.0,0.0,2.462398,0.0,NaN,0.602060,Blount,AL
5,1011,24.0,24.0,24.0,24.0,NaN,NaN,NaN,NaN,NaN,...,NaN,0.041393,NaN,NaN,3.431364,NaN,NaN,0.000000,Bullock,AL
6,1013,8.0,8.0,8.0,8.0,NaN,NaN,NaN,NaN,NaN,...,NaN,0.000000,NaN,NaN,2.954243,NaN,NaN,0.000000,Butler,AL
7,1015,40.0,40.0,40.0,40.0,NaN,NaN,NaN,NaN,NaN,...,NaN,0.000000,NaN,NaN,2.204120,NaN,NaN,0.397940,Calhoun,AL
8,1017,16.0,16.0,16.0,16.0,NaN,NaN,NaN,NaN,NaN,...,0.518514,0.176091,0.0,0.0,2.115056,0.0,NaN,0.454845,Chambers,AL
9,1019,164.0,164.0,164.0,164.0,NaN,NaN,NaN,NaN,NaN,...,NaN,0.079181,NaN,NaN,2.698970,NaN,NaN,0.477121,Cherokee,AL

In [85]:
#row sum
import numpy as np

ucmr_by_county2['indices.sum'] = np.nansum(ucmr_by_county2.filter(regex=("indices.max*")), axis=1)
ucmr_by_county2['counts.sum'] = np.nansum(ucmr_by_county2.filter(regex=("indices.count*")), axis=1)

In [74]:
ucmr_by_county2['voc.indices.avg'] = ucmr_by_county2[['indices.max.1,2,3-trichloropropane',
                                        'indices.max.1,3-butadiene',
                                        'indices.max.chloromethane',
                                        'indices.max.1,1-dichloroethane',
                                        'indices.max.bromomethane',
                                        'indices.max.HCFC-22',
                                        'indices.max.Halon 1011']].apply(lambda row: np.nanmean(row),axis=1)
ucmr_by_county2['soc.indices.avg'] = ucmr_by_county2[['indices.max.1,4-dioxane']].apply(lambda row: np.nanmean(row),axis=1)
ucmr_by_county2['metal.indices.avg'] = ucmr_by_county2[['indices.max.vanadium',
                                                       'indices.max.molybdenum',
                                                       'indices.max.cobalt',
                                                       'indices.max.strontium',
                                                       'indices.max.chromium',
                                                       'indices.max.chromium-6']].apply(lambda row: np.nanmean(row),axis=1)
ucmr_by_county2['dbp.indices.avg'] = ucmr_by_county2[['indices.max.chlorate']].apply(lambda row: np.nanmean(row),axis=1)
ucmr_by_county2['pfas.indices.avg'] = ucmr_by_county2[['indices.max.PFOS',
                                                       'indices.max.PFOA',
                                                       'indices.max.PFNA',
                                                       'indices.max.PFHpA',
                                                       'indices.max.PFHxS',
                                                       'indices.max.PFBS']].apply(lambda row: np.nanmean(row),axis=1)
ucmr_by_county2['horm.indices.avg'] = ucmr_by_county2[['indices.max.17-beta-estradiol',
                                                       'indices.max.17-alpha-ethynylestrad',
                                                       'indices.max.estriol',
                                                       'indices.max.estrone',
                                                       'indices.max.equilin',
                                                       'indices.max.testosterone',
                                                       'indices.max.4-androstene-3,17-dion']].apply(lambda row: np.nanmean(row),axis=1)

/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:7: RuntimeWarning: Mean of empty slice
  import sys
/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:8: RuntimeWarning: Mean of empty slice

/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:14: RuntimeWarning: Mean of empty slice

/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:15: RuntimeWarning: Mean of empty slice
  from ipykernel import kernelapp as app
/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:21: RuntimeWarning: Mean of empty slice
/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:28: RuntimeWarning: Mean of empty slice

In [86]:
ucmr_by_county2.head(10)

,COUNTY,"AnalyticalResultValue.count.1,1-dichloroethane","AnalyticalResultValue.count.1,2,3-trichloropropane","AnalyticalResultValue.count.1,3-butadiene","AnalyticalResultValue.count.1,4-dioxane",AnalyticalResultValue.count.17-alpha-ethynylestrad,AnalyticalResultValue.count.17-beta-estradiol,"AnalyticalResultValue.count.4-androstene-3,17-dion",AnalyticalResultValue.count.Aerobic spores,AnalyticalResultValue.count.E. coli,...,state,indices.avg,counts.sum,voc.indices.avg,soc.indices.avg,metal.indices.avg,dbp.indices.avg,pfas.indices.avg,horm.indices.avg,indices.sum
0,1001,59.0,59.0,59.0,59.0,4.0,4.0,4.0,NaN,NaN,...,AL,0.279086,1916.0,0.000000,0.000000,1.043131,0.000000,0.050172,0.0,9.209826
1,1003,122.0,122.0,122.0,122.0,NaN,NaN,NaN,NaN,NaN,...,AL,0.459404,2912.0,0.117701,0.602060,1.129059,1.447158,0.000000,NaN,9.647478
2,1005,14.0,14.0,14.0,14.0,32.0,32.0,32.0,NaN,NaN,...,AL,0.099925,616.0,0.000000,0.000000,0.466315,0.000000,0.000000,0.0,2.797890
3,1007,8.0,8.0,8.0,8.0,8.0,8.0,8.0,NaN,NaN,...,AL,0.230455,280.0,0.000000,0.000000,0.773303,1.812913,0.000000,0.0,6.452732
4,1009,80.0,80.0,80.0,80.0,NaN,NaN,NaN,NaN,NaN,...,AL,0.349895,2242.0,0.000000,0.535113,0.896878,2.113943,0.177824,NaN,9.097270
5,1011,24.0,24.0,24.0,24.0,NaN,NaN,NaN,NaN,NaN,...,AL,0.165369,630.0,0.000000,0.000000,0.578793,0.000000,0.000000,NaN,3.472756
6,1013,8.0,8.0,8.0,8.0,NaN,NaN,NaN,NaN,NaN,...,AL,0.140678,224.0,0.000000,0.000000,0.492374,0.000000,0.000000,NaN,2.954243
7,1015,40.0,40.0,40.0,40.0,NaN,NaN,NaN,NaN,NaN,...,AL,0.348281,1120.0,0.103857,1.711204,0.642418,1.021189,0.000000,NaN,7.313901
8,1017,16.0,16.0,16.0,16.0,NaN,NaN,NaN,NaN,NaN,...,AL,0.277146,480.0,0.000000,0.516630,0.732082,1.778151,0.000000,NaN,7.205788
9,1019,164.0,164.0,164.0,164.0,NaN,NaN,NaN,NaN,NaN,...,AL,0.410303,4592.0,0.000000,0.535113,0.816728,2.113943,0.177824,NaN,8.616370

In [83]:
from scipy import stats
stats.describe(ucmr_by_county2['metal.indices.avg'],nan_policy='omit')
#stats.describe(ucmr_by_county2['metal.indices.avg'],nan_policy='omit')

DescribeResult(nobs=2073, minmax=(masked_array(data = 0.2126925525,
             mask = False,
       fill_value = 1e+20)
, masked_array(data = 2.570160056666667,
             mask = False,
       fill_value = 1e+20)
), mean=0.94897937870517768, variance=0.13234977501388076, skewness=masked_array(data = 0.8957156342109736,
             mask = False,
       fill_value = 1e+20)
, kurtosis=0.81746640789119995)

In [87]:
ucmr_by_county2.to_csv('ucmrByCounty_final.csv')